In [36]:
import numpy as np
import pandas as pd

In [37]:
d=pd.read_csv('/kaggle/input/credit-card/credit.csv')
d.head(10)

,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity,Balance
0,14.891,3606,283,2,34,11,Male,No,Yes,Caucasian,333
1,106.025,6645,483,3,82,15,Female,Yes,Yes,Asian,903
2,104.593,7075,514,4,71,11,Male,No,No,Asian,580
3,148.924,9504,681,3,36,11,Female,No,No,Asian,964
4,55.882,4897,357,2,68,16,Male,No,Yes,Caucasian,331
5,80.180,8047,569,4,77,10,Male,No,No,Caucasian,1151
6,20.996,3388,259,2,37,12,Female,No,No,African American,203
7,71.408,7114,512,2,87,9,Male,No,No,Asian,872
8,15.125,3300,266,5,66,13,Female,No,No,Caucasian,279
9,71.061,6819,491,3,41,19,Female,Yes,Yes,African American,1350

In [38]:
d1 = pd.get_dummies(d['Gender'], drop_first=True).astype(int) 
d = d.drop('Gender', axis=1)
d = pd.concat([d, d1], axis=1)

In [39]:
#For Student Section
d['Student'] = d['Student'].map({'Yes': 1, 'No': 0})
#For Married Section
d['Married'] = d['Married'].map({'Yes': 1, 'No': 0})
# For Ethnicity
d['Ethnicity'] = d['Ethnicity'].map({'Caucasian': 1, 'Asian': 2,'African American':3})

In [40]:
d.head(10)

,Income,Limit,Rating,Cards,Age,Education,Student,Married,Ethnicity,Balance,Male
0,14.891,3606,283,2,34,11,0,1,1,333,1
1,106.025,6645,483,3,82,15,1,1,2,903,0
2,104.593,7075,514,4,71,11,0,0,2,580,1
3,148.924,9504,681,3,36,11,0,0,2,964,0
4,55.882,4897,357,2,68,16,0,1,1,331,1
5,80.180,8047,569,4,77,10,0,0,1,1151,1
6,20.996,3388,259,2,37,12,0,0,3,203,0
7,71.408,7114,512,2,87,9,0,0,2,872,1
8,15.125,3300,266,5,66,13,0,0,1,279,0
9,71.061,6819,491,3,41,19,1,1,3,1350,0

In [41]:
X=d.iloc[:,[0,2,3,4,5,6,7,8,9,10]]
Y=d.iloc[:,1]

In [42]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [43]:
from sklearn.ensemble import RandomForestRegressor
m=RandomForestRegressor(n_estimators=100)
m.fit(X_train,y_train)

RandomForestRegressor()

In [45]:
from sklearn.metrics import r2_score
y_pred=m.predict(X_test)
acc=r2_score(y_pred,y_test)
acc*100.0

99.04157667972838